In [1]:
import pandas as pd
import numpy as np

In [14]:
path_csvfile = 'pyECLAT/data/base2.csv' #path of csv file
df_base2 = pd.read_csv(path_csvfile, header=None) #create dataframe. Its need set up header=None
df_base2

,0,1,2,3,4,5,6
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN
...,...,...,...,...,...,...,...
2996,green tea,NaN,NaN,NaN,NaN,NaN,NaN
2997,shrimp,cake,NaN,NaN,NaN,NaN,NaN
2998,ham,ground beef,mineral water,NaN,NaN,NaN,NaN
2999,burgers,frozen vegetables,whole wheat pasta,mineral water,chocolate,eggs,blueberries
3000,whole wheat pasta,eggs,cake,french fries,green tea,NaN,NaN

In [15]:
from pyECLAT import ECLAT

In [16]:
eclat_class = ECLAT(data=df_base2, verbose=True)

100%|██████████| 119/119 [00:00<00:00, 416.32it/s]
100%|██████████| 119/119 [00:00<00:00, 13700.10it/s]
100%|██████████| 119/119 [00:00<00:00, 3786.36it/s]

In [17]:
#Cheking the binary dataframe generate
#Check if a dataframe like this has been generated. The product names are now in the column name (no repetition)
eclat_class.df_bin

,parmesan cheese,chocolate bread,tomato juice,cereals,whole wheat pasta,energy drink,babies food,green beans,spaghetti,vegetables mix,...,green grapes,mint,chocolate,whole wheat rice,sandwich,white wine,chicken,salt,black tea,olive oil
0,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2999,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3000,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
get_ECLAT_indexes, get_ECLAT_supports = eclat_class.fit(min_support=0.04,
                                                           min_combination=1,
                                                           max_combination=4,
                                                           separator=' & ',
                                                           verbose=True)

12it [00:00, 117.51it/s]

Combination 1 by 1

27it [00:00, 116.71it/s]
44it [00:00, 208.36it/s]

Combination 2 by 2

351it [00:01, 210.22it/s]
19it [00:00, 189.80it/s]

Combination 3 by 3

2925it [00:14, 201.61it/s]
17it [00:00, 168.95it/s]

Combination 4 by 4

17550it [01:34, 184.82it/s]

In [33]:
#Supports values of products 
get_ECLAT_supports

{'spaghetti': 0.18293902032655782,
 'burgers': 0.08563812062645784,
 'soup': 0.054315228257247584,
 'turkey': 0.06597800733088971,
 'cooking oil': 0.04798400533155615,
 'frozen smoothie': 0.04798400533155615,
 'pancakes': 0.07864045318227257,
 'eggs': 0.17727424191936023,
 'cookies': 0.07697434188603798,
 'frozen vegetables': 0.09196934355214928,
 'escalope': 0.07064311896034656,
 'milk': 0.12695768077307565,
 'ground beef': 0.09363545484838387,
 'tomatoes': 0.06864378540486504,
 'low fat yogurt': 0.05664778407197601,
 'cake': 0.07697434188603798,
 'shrimp': 0.0773075641452849,
 'champagne': 0.042652449183605466,
 'green tea': 0.11329556814395202,
 'grated cheese': 0.055314895034988334,
 'mineral water': 0.23692102632455847,
 'herb & pepper': 0.05031656114628457,
 'french fries': 0.15428190603132289,
 'chocolate': 0.1616127957347551,
 'whole wheat rice': 0.045318227257580806,
 'chicken': 0.05664778407197601,
 'olive oil': 0.06597800733088971,
 'spaghetti & mineral water': 0.06064645118293902,
 'eggs & mineral water': 0.04798400533155615,
 'milk & mineral water': 0.048317227590803064,
 'mineral water & chocolate': 0.04765078307230923}

In [45]:
#Index of the occurrence of products together
#This index refers to the original dataframe
get_ECLAT_indexes

In [50]:
#This function will search for all possible combinations that have support > 0.02 (in this case)
get_ECLAT_indexes_all, get_ECLAT_supports_all = eclat_class.fit_all(min_support=0.02,
                                                           separator=' & ',
                                                           verbose=True)

11it [00:00, 102.95it/s]

Combination 1 by 1

47it [00:00, 105.29it/s]
21it [00:00, 207.00it/s]

Combination 2 by 2

1081it [00:05, 208.31it/s]
19it [00:00, 183.13it/s]

Combination 3 by 3

16215it [01:20, 200.32it/s]

Stopping in combination 3 by 3. All supports = 0.

In [51]:
get_ECLAT_supports_all

{'whole wheat pasta': 0.03032322559146951,
 'energy drink': 0.023992002665778073,
 'spaghetti': 0.18293902032655782,
 'red wine': 0.02865711429523492,
 'burgers': 0.08563812062645784,
 'soup': 0.054315228257247584,
 'turkey': 0.06597800733088971,
 'cooking oil': 0.04798400533155615,
 'salmon': 0.03898700433188937,
 'frozen smoothie': 0.04798400533155615,
 'hot dogs': 0.025658113962012664,
 'light mayo': 0.02332555814728424,
 'yogurt cake': 0.023992002665778073,
 'pancakes': 0.07864045318227257,
 'eggs': 0.17727424191936023,
 'avocado': 0.035654781739420195,
 'cookies': 0.07697434188603798,
 'energy bar': 0.026657780739753417,
 'butter': 0.029656781072975674,
 'brownies': 0.023658780406531157,
 'frozen vegetables': 0.09196934355214928,
 'escalope': 0.07064311896034656,
 'meatballs': 0.02165944685104965,
 'milk': 0.12695768077307565,
 'ground beef': 0.09363545484838387,
 'oil': 0.023658780406531157,
 'muffins': 0.02299233588803732,
 'tomatoes': 0.06864378540486504,
 'low fat yogurt': 0.05664778407197601,
 'fresh bread': 0.03032322559146951,
 'honey': 0.03865378207264245,
 'french wine': 0.02165944685104965,
 'cake': 0.07697434188603798,
 'shrimp': 0.0773075641452849,
 'fresh tuna': 0.025658113962012664,
 'champagne': 0.042652449183605466,
 'green tea': 0.11329556814395202,
 'grated cheese': 0.055314895034988334,
 'mineral water': 0.23692102632455847,
 'herb & pepper': 0.05031656114628457,
 'pepper': 0.02865711429523492,
 'ham': 0.027657447517494167,
 'french fries': 0.15428190603132289,
 'chocolate': 0.1616127957347551,
 'whole wheat rice': 0.045318227257580806,
 'chicken': 0.05664778407197601,
 'olive oil': 0.06597800733088971,
 'spaghetti & burgers': 0.023992002665778073,
 'spaghetti & eggs': 0.03265578140619793,
 'spaghetti & frozen vegetables': 0.030989670109963344,
 'spaghetti & milk': 0.03865378207264245,
 'spaghetti & ground beef': 0.03598800399866711,
 'spaghetti & tomatoes': 0.023658780406531157,
 'spaghetti & shrimp': 0.024991669443518827,
 'spaghetti & mineral water': 0.06064645118293902,
 'spaghetti & french fries': 0.02165944685104965,
 'spaghetti & chocolate': 0.03732089303565478,
 'spaghetti & olive oil': 0.021326224591802733,
 'burgers & eggs': 0.025324891702765744,
 'burgers & mineral water': 0.023992002665778073,
 'soup & mineral water': 0.025658113962012664,
 'pancakes & mineral water': 0.022325891369543487,
 'eggs & milk': 0.027990669776741087,
 'eggs & green tea': 0.020659780073308896,
 'eggs & mineral water': 0.04798400533155615,
 'eggs & french fries': 0.03432189270243252,
 'eggs & chocolate': 0.028323892035988004,
 'frozen vegetables & mineral water': 0.03698767077640786,
 'milk & ground beef': 0.02165944685104965,
 'milk & mineral water': 0.048317227590803064,
 'milk & chocolate': 0.026991002999000334,
 'ground beef & mineral water': 0.03698767077640786,
 'tomatoes & mineral water': 0.024991669443518827,
 'cake & mineral water': 0.023658780406531157,
 'shrimp & mineral water': 0.027990669776741087,
 'green tea & french fries': 0.022325891369543487,
 'mineral water & french fries': 0.02299233588803732,
 'mineral water & chocolate': 0.04765078307230923,
 'mineral water & olive oil': 0.02732422525824725,
 'french fries & chocolate': 0.027657447517494167}